#!/bin/bash

echo ""
echo "####### run this script once only ####### "
echo ""

echo "adding keys to ${HOME}/.ssh/ ..."

# move stuff to local .ssh folder
cat config >> ${HOME}/.ssh/config
cp cf-key ${HOME}/.ssh/
cp cf-key.pub ${HOME}/.ssh/

echo "changing ownerip of keys ..."
# change ownership
chown $(whoami) ${HOME}/.ssh/cf-key
chown $(whoami) ${HOME}/.ssh/cf-key.pub

echo "done"

