#!/bin/bash

echo ""
echo "run this script once only"
echo ""

# move stuff to local .ssh folder
cat config >> ${HOME}/.ssh/config
cp cf-key ${HOME}/.ssh/
cp cf-key.pub ${HOME}/.ssh/

# change ownership
chown $(whoami) ${HOME}/.ssh/cf-key
chown $(whoami) ${HOME}/.ssh/cf-key.pub


