#!/bin/bash

function main() {
    # get image names
    images=($(ls images))

    if [ "${1}" == "" ]; then
        echo -e "\nERROR: first argument required. provide 1 of: [${images[@]} all]\n"
    elif [ "${1}" == "all" ]; then
        for image in ${images[@]}; do
            echo ""
            echo "####### building ${image} image ####### "
            echo ""
            docker build -f ./images/${image}/Dockerfile --no-cache -t ${image}:bdi . --pull
        done
        echo "done"
    elif [[ "${images[@]}" =~ "${1}" ]]; then
        docker build -f ./images/${1}/Dockerfile --no-cache -t ${1}:bdi . --pull
    else
        echo -e "\nERROR: invalid argument. provide 1 of: [${images[@]} all]\n"
    fi
}

main $@
