#!/bin/bash

function main() {
    if [ "$1" == "" ]; then
        host="node1"
    else
        host=$1
    fi
    
    trgt="docker_scripts-${host}-1"
    echo ""
    echo "########## logging into ${trgt} ########## "
    echo ""
    docker exec -it ${trgt} bash
}

main $@
